<?php
return array(
    'languages' => array(
        'en_US' => 'English (United States)',
        'ru_RU' => 'Русский (Россия)',
        'uk_UA' => 'Український (Україна)',
        'sq_AL' => 'Shqiptar (Shqipëri)',
        'fr_FR' => 'Français (France)',
        'nl_NL' => 'Nederlands (Nederland)',
        'nl_BE' => 'Nederlands (België)',        
        'sr_RS' => 'Српски језик (Србија)',
        'lt_LT' => 'Lietuvių kalba (Lietuva)',
        'es_EC' => 'Español (Ecuador)',
        'es_ES' => 'Español (España)',
        'pt_PT' => 'Português (Portugal)',
        'sl_SI' => 'Slovenščina (Slovenija)',
        'ro_RO' => 'Română (România)',
        'de_DE' => 'Deutsch (Deutschland)',
        'it_IT' => 'Italiano (Italia)',
        'tr_TR' => 'Türkçe (Türkiye)', 
        'hr_HR' => 'Hrvatski (Hrvatska)',
        'bg_BG' => 'Български (България)',
        'pl_PL' => 'Polski (Polska)',
        'ca_CA' => 'Català (Catalunya)',
        'fa_IR' => 'فارسی',
        'el_GR' => 'Ελληνικά (Ελλάδα)',
        'da_DK' => 'Dansk (Danmark)',
    ),   
    'wcp_weather_widget_templates' => array(
        'default' => 'Default',
        'compact' => 'Compact',
    ),
    'wcp_weather_mini_widget_templates' => array(
        'default' => 'Default',
    ),    
    'wcp_weather_templates' => array(
        'default' => 'Default',
        'compact' => 'Compact',
    ),        
);
